version: "3"

services: 
    labsite:
        build: .
        volumes: 
            - ~/webserver/database/:/database/
            - ~/webserver/static/:/app/static/
        env_file: 
            - ~/webserver/.env
        restart: always
        ports: 
            - 8000:8000
            - 465:465
        command: gunicorn -w 4 --bind 0.0.0.0:8000 labsite:app

    nginx:
        image: nginx:latest
        volumes: 
            - ~/webserver/nginx/:/etc/nginx/conf.d:ro
        restart: always
        ports: 
            - 80:80
        depends_on: 
            - labsite
