version: "3"

services: 
    labsite:
        build: webserver/
        volumes: 
            - ./database/:/database/
            - ./static/:/app/static/
        env_file: 
            - .env
        ports: 
            - 8000:8000
            - 465:465
        command: gunicorn -w 4 --bind 0.0.0.0:8000 labsite:app

    nginx:
        image: nginx:latest
        volumes: 
            - ./nginx/:/etc/nginx/conf.d:ro
        ports: 
            - 80:80
        depends_on: 
            - labsite