"""empty message

Revision ID: 028a54de3070
Revises: e33a4dc4dd7e
Create Date: 2022-02-15 11:30:14.798281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '028a54de3070'
down_revision = 'e33a4dc4dd7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=256), nullable=True),
    sa.Column('organization', sa.String(length=256), nullable=True),
    sa.Column('position', sa.String(length=256), nullable=True),
    sa.Column('phone', sa.String(length=256), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('readed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('response')
    # ### end Alembic commands ###
