"""empty message

Revision ID: 159aff38c2c9
Revises: 21b46d74f090
Create Date: 2020-05-25 13:09:16.245714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '159aff38c2c9'
down_revision = '21b46d74f090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_news_Title', table_name='news')
    op.create_index(op.f('ix_news_Title'), 'news', ['Title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_Title'), table_name='news')
    op.create_index('ix_news_Title', 'news', ['Title'], unique=False)
    # ### end Alembic commands ###
