"""patent

Revision ID: 58e6608c755d
Revises: d979aae04d26
Create Date: 2020-06-03 10:04:28.268243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58e6608c755d'
down_revision = 'd979aae04d26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patent')
    # ### end Alembic commands ###
