"""empty message

Revision ID: b5db3be9ffda
Revises: e33a4dc4dd7e
Create Date: 2021-07-26 11:36:39.825787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5db3be9ffda'
down_revision = 'e33a4dc4dd7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Image', sa.String(length=32), nullable=True),
    sa.Column('Description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Image', sa.String(length=32), nullable=True),
    sa.Column('Title', sa.String(length=32), nullable=True),
    sa.Column('Description', sa.String(length=256), nullable=True),
    sa.Column('Fulltext', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_Title'), 'news', ['Title'], unique=True)
    op.create_table('patent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(length=32), nullable=True),
    sa.Column('SecondName', sa.String(length=32), nullable=True),
    sa.Column('MiddleName', sa.String(length=32), nullable=True),
    sa.Column('Image', sa.String(length=32), nullable=True),
    sa.Column('Position', sa.String(length=32), nullable=True),
    sa.Column('Info', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Year', sa.Integer(), nullable=True),
    sa.Column('Text', sa.String(), nullable=True),
    sa.Column('DOI', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publication_DOI'), 'publication', ['DOI'], unique=False)
    op.create_table('research',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Image', sa.String(length=32), nullable=True),
    sa.Column('Title', sa.String(length=32), nullable=True),
    sa.Column('Description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_Title'), 'research', ['Title'], unique=False)
    op.create_table('slider_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Index', sa.Integer(), nullable=True),
    sa.Column('Image', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slider_image_Index'), 'slider_image', ['Index'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_slider_image_Index'), table_name='slider_image')
    op.drop_table('slider_image')
    op.drop_index(op.f('ix_research_Title'), table_name='research')
    op.drop_table('research')
    op.drop_index(op.f('ix_publication_DOI'), table_name='publication')
    op.drop_table('publication')
    op.drop_table('project')
    op.drop_table('person')
    op.drop_table('patent')
    op.drop_index(op.f('ix_news_Title'), table_name='news')
    op.drop_table('news')
    op.drop_table('gallery_image')
    # ### end Alembic commands ###
