"""empty message

Revision ID: c11c64b391ab
Revises: fd5354b40524
Create Date: 2022-03-02 15:22:44.672931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c11c64b391ab'
down_revision = 'fd5354b40524'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response', sa.Column('verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('response', 'verified')
    # ### end Alembic commands ###
