"""empty message

Revision ID: d1cadbea57ff
Revises: 
Create Date: 2020-05-13 13:34:20.573163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1cadbea57ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Image', sa.String(length=32), nullable=True),
    sa.Column('Title', sa.String(length=32), nullable=True),
    sa.Column('Description', sa.String(length=256), nullable=True),
    sa.Column('Fulltext', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_Title'), 'news', ['Title'], unique=False)
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(length=32), nullable=True),
    sa.Column('SecondName', sa.String(length=32), nullable=True),
    sa.Column('MiddleName', sa.String(length=32), nullable=True),
    sa.Column('Image', sa.String(length=32), nullable=True),
    sa.Column('Position', sa.String(length=32), nullable=True),
    sa.Column('Info', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Image', sa.String(length=32), nullable=True),
    sa.Column('Title', sa.String(length=32), nullable=True),
    sa.Column('Description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_Title'), 'research', ['Title'], unique=False)
    op.create_table('slider_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Index', sa.Integer(), nullable=True),
    sa.Column('Image', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slider_image_Index'), 'slider_image', ['Index'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slider_image_Index'), table_name='slider_image')
    op.drop_table('slider_image')
    op.drop_index(op.f('ix_research_Title'), table_name='research')
    op.drop_table('research')
    op.drop_table('person')
    op.drop_index(op.f('ix_news_Title'), table_name='news')
    op.drop_table('news')
    # ### end Alembic commands ###
