"""empty message

Revision ID: d979aae04d26
Revises: 159aff38c2c9
Create Date: 2020-05-27 15:09:28.686666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd979aae04d26'
down_revision = '159aff38c2c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Year', sa.Integer(), nullable=True),
    sa.Column('Text', sa.String(), nullable=True),
    sa.Column('DOI', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publication_DOI'), 'publication', ['DOI'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publication_DOI'), table_name='publication')
    op.drop_table('publication')
    # ### end Alembic commands ###
