"""empty message

Revision ID: fd5354b40524
Revises: 9363654d31b6
Create Date: 2022-02-15 14:35:56.260387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd5354b40524'
down_revision = '9363654d31b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response', sa.Column('datetime', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('response', 'datetime')
    # ### end Alembic commands ###
